name: clean_me_partner
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.2
  firebase_core: ^1.13.1
  firebase_auth: ^3.3.9
  cloud_firestore: ^3.1.10
  firebase_storage: ^10.2.9
  flutter_easyloading: ^3.0.3
  url_launcher: ^6.0.20
  map_launcher: ^2.2.1+1
  location: ^4.3.0
  geocode: ^1.0.1
  permission_handler: ^9.2.0
  geolocator: ^8.2.0
  google_maps_flutter: ^2.1.2
  percent_indicator: ^4.0.0
  email_validator: ^2.0.1
  image_picker: ^0.8.4+11
  cached_network_image: ^3.2.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/gifs/

  fonts:
    - family: Netverbatim
      fonts:
        - asset: fonts/Netverbatim_medium.ttf

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
